version: '3.8'

services:
  user-service:
    build: ./services/user-service
    ports:
      - "8001:8001"
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  order-service:
    build: ./services/order-service
    ports:
      - "8002:8002"
    depends_on:
      user-service:
        condition: service_healthy
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8002/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  payment-service:
    build: ./services/payment-service
    ports:
      - "8003:8003"
    depends_on:
      order-service:
        condition: service_healthy
    networks:
      - microservices-net
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8003/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  microservices-net:
    driver: bridge