apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: microservices
  labels:
    app: user-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: microservices
  labels:
    app: order-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service-sa
  namespace: microservices
  labels:
    app: payment-service